apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  labels:
    name: elastic-pod
    app: userservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elastic-pod
      app: userservice-app
  template:
    metadata:
      name: elastic-pod
      labels:
        name: elastic-pod
        app: userservice-app
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
          readinessProbe:
            httpGet:
              port: 8083
              path: /
          livenessProbe:
            httpGet:
              port: 8083
              path: /
          env:
            - name: http.host
              value: "0.0.0.0"
            - name: transport.host
              value: "127.0.0.1"
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200