apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka-service
    app: userservice-app
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    name: kafka-pod
    app: userservice-app