apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    name: kafka-pod
    app: userservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
        name: kafka-pod
        app: userservice-app
  template:
    metadata:
      name: kafka-pod
      labels:
        name: kafka-pod
        app: userservice-app
    spec:
      containers:
        - name: kafka
          image: debezium/kafka:1.1
          readinessProbe:
            httpGet:
              port: 8083
              path: /
          livenessProbe:
            httpGet:
              port: 8083
              path: /
          env:
            - name: ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
          ports:
            - containerPort: 9092