apiVersion: v1
kind: Service
metadata:
  name: kafkaconnect-service
  labels:
    name: kafkaconnect-service
    app: userservice-app
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    name: kafkaconnect-pod
    app: userservice-app