apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres-service
    app: userservice-app
spec:
  ports:
    - port: 54321
      targetPort: 5432
  selector:
    name: postgres-pod
    app: userservice-app
