apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    name: userservice-service
    app: userservice-app
spec:
  type: LoadBalancer
  ports:
    - port: 8101
      targetPort: 8101
  selector:
    name: userservice-pod
    app: userservice-app