apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: userservice-pod
      app: userservice-app
  template:
    metadata:
      name: userservice-pod
      labels:
        name: userservice-pod
        app: userservice-app
    spec:
      containers:
        - name: userservice
          image: olnik27/userservice
          readinessProbe:
            httpGet:
              port: 8083
              path: /
          livenessProbe:
            httpGet:
              port: 8083
              path: /
          ports:
            - containerPort: 8081